### ISSUE TITLE
Update from 2.8 to 3 doesnt work

### ISSUE THREAD

**Issue by RobDiek** [YunoHost-Apps/nodebb_ynh#55]
### Describe the bug

Updating to the new v3 Version at yunohost doesnt work
### Context

- Hardware: VPS bought online
- YunoHost version: 11.1.9 stable
- I have access to my server: *Through SSH and through the webadmin 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?:no
- Using, or trying to install package version/branch:              v2.8.14             -> v3.1.4
- 
- If upgrading, current package version: *can be found in the admin, or with `yunohost app info $app_id`*

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*

### Expected behavior

App should be updated
### Logs

https://[paste.yunohost.org/raw/pasekocufe](https://paste.yunohost.org/raw/pasekocufe)

2. Bringing base dependencies up to date...  started
2023-05-21 11:00:58,013: DEBUG - Error installing dependencies!
2023-05-21 11:00:58,014: DEBUG - message: Command failed: npm install --omit=dev
2023-05-21 11:00:58,014: DEBUG - stdout: null
2023-05-21 11:00:58,014: DEBUG - stderr: null
2023-05-21 11:00:58,021: DEBUG - 2023-05-21T09:00:58.019Z [4567/1173452] - [31merror[39m: uncaughtException: Command failed: npm install --omit=dev
2023-05-21 11:00:58,021: DEBUG - Error: Command failed: npm install --omit=dev
2023-05-21 11:00:58,021: DEBUG -     at checkExecSyncError (node:child_process:861:11)
2023-05-21 11:00:58,022: DEBUG -     at Object.execSync (node:child_process:932:15)
2023-05-21 11:00:58,022: DEBUG -     at Object.pkgInstall.installAll (/var/www/nodebb/src/cli/package-install.js:129:9)
2023-05-21 11:00:58,022: DEBUG -     at Object.handler (/var/www/nodebb/src/cli/upgrade.js:22:19)
2023-05-21 11:00:58,022: DEBUG -     at runSteps (/var/www/nodebb/src/cli/upgrade.js:55:16)
2023-05-21 11:00:58,022: DEBUG -     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by RobDiek** [comment]
I now started the CMD command to update to testing version: 

154429 ERROR Could not upgrade nodebb: An error occurred inside the app upgrade script
154430 INFO The operation 'Upgrade the 'nodebb' app' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20230521-090844-app_upgrade-nodebb' to get help
154450 WARNING Here's an extract of the logs before the crash. It might help debugging the error:
154450 INFO DEBUG -
154451 INFO DEBUG - Updating NodeBB...
154451 INFO DEBUG -
154451 INFO DEBUG - 1. Updating package.json file with defaults...  OK
154451 INFO DEBUG -
154451 INFO DEBUG - 2. Bringing base dependencies up to date...  started
154451 INFO DEBUG - Error installing dependencies!
154451 INFO DEBUG - message: Command failed: npm install --omit=dev
154451 INFO DEBUG - stdout: null
154451 INFO DEBUG - stderr: null
154451 INFO DEBUG - 2023-05-21T09:09:49.525Z [4567/1205221] - error: uncaughtException: Command failed: npm install --omit=dev
154451 INFO DEBUG - Error: Command failed: npm install --omit=dev
154451 INFO DEBUG -     at checkExecSyncError (node:child_process:861:11)
154451 INFO DEBUG -     at Object.execSync (node:child_process:932:15)
154452 INFO DEBUG -     at Object.pkgInstall.installAll (/var/www/nodebb/src/cli/package-install.js:129:9)
154452 INFO DEBUG -     at Object.handler (/var/www/nodebb/src/cli/upgrade.js:22:19)
154452 INFO DEBUG -     at runSteps (/var/www/nodebb/src/cli/upgrade.js:55:16)
154452 INFO DEBUG -     at processTicksAndRejections (node:internal/process/task_queues:96:5)
154452 INFO DEBUG -     at async Object.runUpgrade [as upgrade] (/var/www/nodebb/src/cli/upgrade.js:85:3) {"date":"Sun May 21 2023 11:09:49 GMT+0200 (Central European Summer Time)","error":{"output":[null,null,null],"pid":1208202,"signal":null,"status":1,"stderr":null,"stdout":null},"exception":true,"os":{"loadavg":[0.98,0.73,0.51],"uptime":1251578.83},"process":{"argv":["/opt/node_n/n/versions/node/16.20.0/bin/node","/var/www/nodebb/nodebb","upgrade"],"cwd":"/var/www/nodebb","execPath":"/opt/node_n/n/versions/node/16.20.0/bin/node","gid":991,"memoryUsage":{"arrayBuffers":285133,"external":3103272,"heapTotal":37486592,"heapUsed":22495728,"rss":73519104},"pid":1205221,"uid":991,"version":"v16.20.0"},"stack":"Error: Command failed: npm install --omit=dev\n    at checkExecSyncError (node:child_process:861:11)\n    at Object.execSync (node:child_process:932:15)\n    at Object.pkgInstall.installAll (/var/www/nodebb/src/cli/package-install.js:129:9)\n    at Object.handler (/var/www/nodebb/src/cli/upgrade.js:22:19)\n    at runSteps (/var/www/nodebb/src/cli/upgrade.js:55:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Object.runUpgrade [as upgrade] (/var/www/nodebb/src/cli/upgrade.js:85:3)","trace":[{"column":11,"file":"node:child_process","function":"checkExecSyncError","line":861,"method":null,"native":false},{"column":15,"file":"node:child_process","function":"Object.execSync","line":932,"method":"execSync","native":false},{"column":9,"file":"/var/www/nodebb/src/cli/package-install.js","function":"Object.pkgInstall.installAll","line":129,"method":"installAll","native":false},{"column":19,"file":"/var/www/nodebb/src/cli/upgrade.js","function":"Object.handler","line":22,"method":"handler","native":false},{"column":16,"file":"/var/www/nodebb/src/cli/upgrade.js","function":"runSteps","line":55,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false},{"column":3,"file":"/var/www/nodebb/src/cli/upgrade.js","function":"async Object.runUpgrade [as upgrade]","line":85,"method":"runUpgrade [as upgrade]","native":false}]}
154452 INFO DEBUG - + ynh_exit_properly
154452 WARNING Upgrade failed ... attempting to restore the satefy backup

**Comment by RobDiek** [comment]
Full update via cmdline log:
https://paste.yunohost.org/raw/oreroxevug
